runtime: nodejs18

env: standard
instance_class: F2

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50 