version: '3.8'

services:
  astrogenie-web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: astrogenie-web
    ports:
      - "80:80"
    restart: unless-stopped
    # Uncomment the following lines if you need to use environment variables
    # environment:
    #   - NODE_ENV=production
    #   - API_URL=https://api.example.com
    # volumes:
    #   - ./logs:/var/log/nginx 