import React, { createContext, useState, useContext } from 'react';

type Language = 'en' | 'es' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: typeof translations[Language];
}

const translations = {
  en: {
    birthChart: 'Birth Chart',
    getStarted: 'Get Started',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    welcome: 'Welcome to AstroConnect',
    subtitle: 'Your personal astrological companion',
    downloadAndroid: 'Download for Android',
    downloadIOS: 'Download for iOS',
    features: 'Features',
    dailyHoroscopes: 'Daily Horoscopes',
    horoscopesDesc: 'Get personalized daily horoscopes based on your zodiac sign.',
    compatibility: 'Compatibility Check',
    compatibilityDesc: 'Check your compatibility with friends and potential partners.',
    tarotReadings: 'Tarot Readings',
    tarotDesc: 'Receive insightful tarot card readings at your fingertips.',
    tryItNow: 'Try it Now',
    home: 'Home',
    about: 'About',
    contact: 'Contact',
    registration: 'Registration',
    createAccount: 'Create your account to access all features',
    login: 'Login',
    password: 'Password',
    name: 'Name',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    resetPasswordDesc: 'Enter your email to receive reset instructions',
    resetPasswordSent: 'Password reset email sent',
    resetPasswordError: 'Failed to send reset email',
    noAccount: "Don't have an account? Sign up",
    haveAccount: 'Already have an account? Login',
    backToLogin: 'Back to Login',
    account: 'Account',
    profile: 'Profile',
    settings: 'Settings',
    favorites: 'Favorites',
    logout: 'Log Out',
    save: 'Save',
    edit: 'Edit',
    language: 'Language',
    notifications: 'Notifications',
    enableNotifications: 'Enable Notifications',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'Are you sure you want to delete your account? This action cannot be undone.',
    noFavorites: 'No favorites yet',
    subscriptionPlans: 'Subscription Plans',
    choosePlan: 'Choose the plan that fits your needs',
    subscribe: 'Subscribe Now',
    premiumFeature: 'Premium Feature',
    upgradeForFullAccess: 'Upgrade to Premium to access detailed compatibility analysis and personalized insights.',
    upgradeToPremium: 'Upgrade to Premium',
    subscription: "Subscription",
    termsAndPolicies: "Terms & Policies",
    heroTitle: 'Discover Your Cosmic Journey',
    heroSubtitle: 'Unlock the secrets of your astrological destiny',
    exploreFeatures: 'Explore Features',
    learnMore: 'Learn More',
    testimonials: 'What Our Users Say',
    downloadApp: 'Download Our App',
    appStore: 'App Store',
    googlePlay: 'Google Play',
    startJourney: 'Start Your Astrological Journey Today',
    freeTrial: 'Start Free Trial',
    noCreditCard: 'No credit card required',
  },
  es: {
    birthChart: 'Birth Chart',
    getStarted: 'Empezar',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    welcome: 'Bienvenido a AstroConnect',
    subtitle: 'Tu compañero astrológico personal',
    downloadAndroid: 'Descargar para Android',
    downloadIOS: 'Descargar para iOS',
    features: 'Características',
    dailyHoroscopes: 'Horóscopos Diarios',
    horoscopesDesc: 'Obtén horóscopos diarios personalizados según tu signo zodiacal.',
    compatibility: 'Verificación de Compatibilidad',
    compatibilityDesc: 'Comprueba tu compatibilidad con amigos y parejas potenciales.',
    tarotReadings: 'Lecturas de Tarot',
    tarotDesc: 'Recibe lecturas de tarot perspicaces al alcance de tu mano.',
    tryItNow: 'Pruébalo Ahora',
    home: 'Inicio',
    about: 'Acerca de',
    contact: 'Contacto',
    registration: 'Registro',
    createAccount: 'Crea tu cuenta para acceder a todas las funciones',
    login: 'Iniciar Sesión',
    password: 'Contraseña',
    name: 'Nombre',
    forgotPassword: '¿Olvidaste tu contraseña?',
    resetPassword: 'Restablecer Contraseña',
    resetPasswordDesc: 'Ingresa tu email para recibir instrucciones',
    resetPasswordSent: 'Email de restablecimiento enviado',
    resetPasswordError: 'Error al enviar el email',
    noAccount: '¿No tienes cuenta? Regístrate',
    haveAccount: '¿Ya tienes cuenta? Inicia sesión',
    backToLogin: 'Volver al inicio de sesión',
    account: 'Cuenta',
    profile: 'Perfil',
    settings: 'Configuración',
    favorites: 'Favoritos',
    logout: 'Cerrar Sesión',
    save: 'Guardar',
    edit: 'Editar',
    language: 'Idioma',
    notifications: 'Notificaciones',
    enableNotifications: 'Activar Notificaciones',
    dangerZone: 'Zona de Peligro',
    deleteAccount: 'Eliminar Cuenta',
    deleteAccountConfirm: '¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.',
    noFavorites: 'Aún no hay favoritos',
    subscriptionPlans: 'Planes de Suscripción',
    choosePlan: 'Elige el plan que se adapte a tus necesidades',
    subscribe: 'Suscribirse Ahora',
    premiumFeature: 'Función Premium',
    upgradeForFullAccess: 'Actualiza a Premium para acceder a análisis de compatibilidad detallados y perspectivas personalizadas.',
    upgradeToPremium: 'Actualizar a Premium',
    subscription: "Suscripción",
    termsAndPolicies: "Términos y Políticas",
    heroTitle: 'Descubre Tu Viaje Cósmico',
    heroSubtitle: 'Desbloquea los secretos de tu destino astrológico',
    exploreFeatures: 'Explorar Características',
    learnMore: 'Saber Más',
    testimonials: 'Lo Que Dicen Nuestros Usuarios',
    downloadApp: 'Descarga Nuestra App',
    appStore: 'App Store',
    googlePlay: 'Google Play',
    startJourney: 'Comienza Tu Viaje Astrológico Hoy',
    freeTrial: 'Comenzar Prueba Gratuita',
    noCreditCard: 'No se requiere tarjeta de crédito',
  },
  ru: {
    birthChart: 'Натальная карта',
    getStarted: 'Начать',
    signIn: 'Войти',
    signUp: 'Регистрация',
    welcome: 'Добро пожаловать в AstroConnect',
    subtitle: 'Ваш личный астрологический помощник',
    downloadAndroid: 'Скачать для Android',
    downloadIOS: 'Скачать для iOS',
    features: 'Возможности',
    dailyHoroscopes: 'Ежедневные гороскопы',
    horoscopesDesc: 'Получайте персонализированные ежедневные гороскопы на основе вашего знака зодиака.',
    compatibility: 'Проверка совместимости',
    compatibilityDesc: 'Проверьте вашу совместимость с друзьями и потенциальными партнерами.',
    tarotReadings: 'Гадания на Таро',
    tarotDesc: 'Получайте проницательные гадания на картах Таро.',
    tryItNow: 'Попробовать сейчас',
    home: 'Главная',
    about: 'О нас',
    contact: 'Контакты',
    registration: 'Регистрация',
    createAccount: 'Создайте аккаунт для доступа ко всем функциям',
    login: 'Вход',
    password: 'Пароль',
    name: 'Имя',
    forgotPassword: 'Забыли пароль?',
    resetPassword: 'Сброс пароля',
    resetPasswordDesc: 'Введите email для получения инструкций',
    resetPasswordSent: 'Email для сброса пароля отправлен',
    resetPasswordError: 'Ошибка отправки email',
    noAccount: 'Нет аккаунта? Зарегистрируйтесь',
    haveAccount: 'Уже есть аккаунт? Войдите',
    backToLogin: 'Вернуться к входу',
    account: 'Аккаунт',
    profile: 'Профиль',
    settings: 'Настройки',
    favorites: 'Избранное',
    logout: 'Выйти',
    save: 'Сохранить',
    edit: 'Редактировать',
    language: 'Язык',
    notifications: 'Уведомления',
    enableNotifications: 'Включить уведомления',
    dangerZone: 'Опасная зона',
    deleteAccount: 'Удалить аккаунт',
    deleteAccountConfirm: 'Вы уверены, что хотите удалить свой аккаунт? Это действие нельзя отменить.',
    noFavorites: 'Пока нет избранного',
    subscriptionPlans: 'Планы подписки',
    choosePlan: 'Выберите план, который подходит вам',
    subscribe: 'Подписаться сейчас',
    premiumFeature: 'Премиум функция',
    upgradeForFullAccess: 'Обновите до премиум для доступа к детальному анализу совместимости и персонализированным инсайтам.',
    upgradeToPremium: 'Обновить до премиум',
    subscription: "Подписка",
    termsAndPolicies: "Условия и политика",
    heroTitle: 'Откройте Свое Космическое Путешествие',
    heroSubtitle: 'Раскройте тайны вашего астрологического предназначения',
    exploreFeatures: 'Исследуйте Возможности',
    learnMore: 'Узнать Больше',
    testimonials: 'Что Говорят Наши Пользователи',
    downloadApp: 'Скачайте Наше Приложение',
    appStore: 'App Store',
    googlePlay: 'Google Play',
    startJourney: 'Начните Свое Астрологическое Путешествие Сегодня',
    freeTrial: 'Начать Бесплатную Пробную Версию',
    noCreditCard: 'Без необходимости вводить данные карты',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const handleLanguageChange = (newLang: Language) => {
    console.log('Changing language to:', newLang); // Debug log
    setLanguage(newLang);
  };

  return (
    <LanguageContext.Provider 
      value={{ 
        language, 
        setLanguage: handleLanguageChange, 
        translations: translations[language] 
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 